CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS allowed_users (
  telegram_id BIGINT PRIMARY KEY,
  name VARCHAR(100) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tx_hash VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL UNIQUE,
  network VARCHAR(32) NOT NULL,
  currency VARCHAR(16) NOT NULL,
  amount DECIMAL(36,12) NOT NULL,
  kind ENUM('income','expense') NOT NULL,
  description VARCHAR(500) NOT NULL DEFAULT '',
  value_irt DECIMAL(24,0) NULL,
  created_by BIGINT NULL,
  created_at DATETIME NOT NULL,
  INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reminders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tx_hash VARCHAR(191) NOT NULL DEFAULT '',
  title VARCHAR(300) NOT NULL,
  interval_days INT NOT NULL DEFAULT 7,
  next_at DATETIME NOT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  send_count INT NOT NULL DEFAULT 0,
  chat_id BIGINT NOT NULL,
  created_at DATETIME NOT NULL,
  INDEX idx_due (active, next_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  ip VARCHAR(64) NOT NULL,
  success TINYINT(1) NOT NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  level VARCHAR(10) NOT NULL,
  message VARCHAR(1000) NOT NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
